### ISSUE TITLE
Create a logo for postile

### ISSUE THREAD

**Issue by autra** [Oslandia/postile#10]
Let's create a logo for postile \o/

**Comment by sylvainbeo** [comment]
@autra @ldgeo Could you write 3 words representing Postile.

**Comment by ldgeo** [comment]
Vector Tile Server

**Comment by sylvainbeo** [comment]
First propositions

![postile_01](https://user-images.githubusercontent.com/632751/67531683-ea366600-f6c3-11e9-8d87-8a05bd66ff77.png)

**Comment by autra** [comment]
Cool! 

I think my favourite right now is either the one on the upper-right corner. or the left one on the middle row. What I like:

- the green
- the fact you can easily extract a favicon
- the simplicity

Can you try adding something that looks like a vector on these 2? Maybe reduce the perspective on the upper-right one?

I also like the general form of the lower-right one, but I think the map inside the tile (with the roads) is too complex. 

Thanks a lot @sylvainbeo !

**Comment by autra** [comment]
A slogan : "PosTile: next generation vector tile server"

**Comment by ldgeo** [comment]
@sylvainbeo nice logos, thanks !

I really like the (2, 2), with `POS` on top and `TILE` below.  Could you add some lines like in the blue logo on the two empty tiles ? 

I also like the (1, 2) like @autra, very simple and clear.

**Comment by sylvainbeo** [comment]
Based on your remarks, quickly :

![postile_02](https://user-images.githubusercontent.com/632751/67577073-0ed02380-f740-11e9-9d0e-e8c1f5d8b05b.png)

Of course, i can also make other propositions.

**Comment by autra** [comment]
Love them! All of them! \o/

If I have to choose, the upper-right or the lower-right. But the middle-left is cool too.

**Comment by sylvainbeo** [comment]
Forgot this one

![postile_03](https://user-images.githubusercontent.com/632751/67577674-3c699c80-f741-11e9-8802-a74d168240f3.png)

**Comment by ldgeo** [comment]
Last one is great. Not a big fan of the green color on the other side. @sylvainbeo your favourite for now ?

**Comment by sylvainbeo** [comment]
Colors can be ajusted of course.

For now, my favorite is the last one, or the ones where the name is inside tiles. The upper left is maybe too common.

**Comment by autra** [comment]
Last one is not my favourite, but I like it too, so it's good for me. So what colour should we choose?

**Comment by sylvainbeo** [comment]
Monochrome or multi-colored ?  (We can try)

**Comment by autra** [comment]
No strong opinion about it... we can try indeed!

**Comment by ldgeo** [comment]
@sylvainbeo as you wish

**Comment by autra** [comment]
So is it the last one?

**Comment by sylvainbeo** [comment]
Sorry i forgot to answer. Should we try some more variation of the last one ? (colors...?)

**Comment by ldgeo** [comment]
@sylvainbeo yes please, on colors  ;-)

**Comment by sylvainbeo** [comment]
Boum, we try different combinaisons

![postile](https://user-images.githubusercontent.com/632751/72824605-cf996c00-3c75-11ea-8c2b-54321cf5caf8.png)

**Comment by autra** [comment]
I think my favourites is still:

![image](https://user-images.githubusercontent.com/1576598/72981152-65e7a200-3ddc-11ea-8a3b-0c5827f830a6.png)

I tend to prefer the green logos over the others.

**Comment by ldgeo** [comment]
ok so let's take the green. That said the red had my preference. we shoudn't take too much time on it. 
Thanks for these nice propositions @sylvainbeo

**Comment by sylvainbeo** [comment]
Ok cool. Tell me where i should push the svg.

**Comment by autra** [comment]
Thanks @sylvainbeo ! In an "assets" directory?
