### ISSUE TITLE
List of available layers and attributes

### ISSUE THREAD

**Issue by bchartier** [Oslandia/postile#3]
Letting the client app to specify the layer (table name) and the attributes to retrieve is nice. But this is not easy for someone that does not have access to the database. It would be nice to have an access point that would list the available layers and attributes.

**Comment by ldgeo** [comment]
indeed, nice feature to add, i will look at this soon. It's a sort of introspection so i advocate to make it optional (a Postile option like `--discover` ?)

**Comment by bchartier** [comment]
What would be the need for making it optional? (I can't see the drawbacks of such a function)

**Comment by delhomer** [comment]
Migrated project, to thread is going on at https://gitlab.com/Oslandia/postile/-/issues/3
