### ISSUE TITLE
Pbf tile url template

### ISSUE THREAD

**Issue by bchartier** [Oslandia/postile#4]
I find it odd to use the following tile url template: `http://localhost:8080/z/x/y.pbf?layer=boundaries&fields=id,name`
The parameter `layer` seems to not be optional. I would suggest to move it just before `z` in order to make the url more restful compliant (in my humble opinion):
`http://localhost:8080/boundaries/z/x/y.pbf?fields=id,name`

[I've not used Postile with the tm2 option, therefore this remark may seem inappropriate for usecases with this option]

**Comment by ldgeo** [comment]
Previously i wanted to allow multiple layers to be queried in parameters but it will be complex to handle fields for each one.
And tm2 is the correct way to handle layer composition so you're right, for direct access (only one layer) `layer` should be part of the URI.

**Comment by ldgeo** [comment]
fixed in 16b7873d95fb1f78e45aab1b9eab9c3a34980db8
