### ISSUE TITLE
Cannot connect to tm2 source

### ISSUE THREAD

**Issue by boldtrn** [Oslandia/postile#6]
When using a tm2 source I get the following error (shortened stacktrace):
```
File "XXX/postile/postile.py", line 57, in setup_db
ConnectionRefusedError: [Errno 111] Connection refused
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```

I use the following command: `postile --cors --tm2 ../../tilelive-swift/openmaptiles.tm2source/data.yml`

When I specify the db connection settings myself using `postile --pgpassword ...` it works.

**Comment by ldgeo** [comment]
@boldtrn sorry for the delay, the PostgreSQL connection parameters needs to be passed on command line, they are not read from the data.yml. 

The tm2source is a format used mainly for the old Mapbox Studio Classic software and is only used partially here (like in OpenMapTiles project).

**Comment by boldtrn** [comment]
Thanks for the update :+1:
